# 00. Pytorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.2


## Introduction to Tensors

### Creating tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html

In [6]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# This is a property of a tensor which gives us the number of dimensions
scalar.ndim

0

In [8]:
# This method just gives us the value of a scalar as a python integer
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
MATRIX[0]

tensor([7, 8])

In [16]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
# We have 3 elements in each list, three lists, and all three lists are in one list, so the shape is [1, 3, 3]
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0075, 0.6338, 0.2702, 0.7179],
        [0.0487, 0.8688, 0.7050, 0.3920],
        [0.3602, 0.1634, 0.1925, 0.5312]])

In [21]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

# IMPORTANT - You don't need to use size=, it is optional

# The main takeaway here is that almost any data can be represented as a tensor
# and images are represented in the format of color channels, height, and width

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# .dtype stands for default type
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.arange(), torch.range() is deprecated
range_one = torch.arange(0, 10)

range_one

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
range_two = torch.arange(start=0, end=1000, step=77)

range_two

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=range_one)

# This will create 10 zeros in the same shape as the range_one range
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
    
    1. Tensors not right datatype, trying to do operations with a float32 and float64 will give you an error
    2. Tensors not right shape, this is when we get into matrix multiplication
    3. Tensors not on the right device, trying to do operations on two tensors that are not the same device will give an error

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device="cuda", # The device on which we want to run, by default "cpu", but you can set to "cuda"
                               requires_grad=False) # Whether or not to track gradients with this tensors operations

float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [31]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [32]:
# Create a tensor
some_tensor = torch.rand(size=(3, 4), device="cuda")
some_tensor

tensor([[0.4072, 0.0551, 0.0116, 0.9687],
        [0.0089, 0.6852, 0.6734, 0.0853],
        [0.7911, 0.9092, 0.2639, 0.8033]], device='cuda:0')

In [33]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}") # tensor.shape and tensor.size() do the same thing
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4072, 0.0551, 0.0116, 0.9687],
        [0.0089, 0.6852, 0.6734, 0.0853],
        [0.7911, 0.9092, 0.2639, 0.8033]], device='cuda:0')
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cuda:0


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

To find patterns in a dataset a neural network will combine these functions.

In [34]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [36]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [37]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

# WHEN YOU CAN USE OPERATORS FROM PYTHON, OTHERWISE USE PYTORCH FUNCTIONS

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

The inner dimensions are (3, **2**) and (**3**, 2), and you can see they are not matching, but in (2, **3**) and (**3**, 2) they do match.

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [39]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [40]:
# Matrix multiplication
torch.matmul(tensor, tensor) # matmul stands for matrix multiplication

tensor(14)

In [41]:
tensor @ tensor # Another way of writing what is in the code cell above

tensor(14)

In [42]:
tensor

tensor([1, 2, 3])

In [43]:
# matrix multiplication by hand
1 * 1 + 2 * 2 + 3 * 3

14

PyTorch's functions are much faster than making your own for loops

In [44]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 997 µs


In [45]:
%%time
torch.matmul(tensor, tensor) # PyTorch's vectorized function is 10 times faster

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common errors in deep learning: shape errors

In [46]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axies or dimensions of a given tensor.

In [47]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [48]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [49]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (smae shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensinos must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A, tensor_B.T).shape

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (smae shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensinos must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

In [50]:
# The matrix multiplication operation works when tensor_A is transposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.T.shape} (smae shape as above), tensor_B.T = {tensor_B.shape}")
print(f"Multiplying: {tensor_A.T.shape} @ {tensor_B.shape} <- inner dimensinos must match")
print("Output:\n")
output = torch.matmul(tensor_A.T, tensor_B)
print(output)
print(f"\nOutput shape: {output.shape}")

torch.matmul(tensor_A.T, tensor_B).shape

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([2, 3]) (smae shape as above), tensor_B.T = torch.Size([3, 2])
Multiplying: torch.Size([2, 3]) @ torch.Size([3, 2]) <- inner dimensinos must match
Output:

tensor([[ 76, 103],
        [100, 136]])

Output shape: torch.Size([2, 2])


torch.Size([2, 2])

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [51]:
# Create a tensor
x = torch.arange(1, 100, 10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [52]:
# Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [53]:
# Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [54]:
# This results in an error because the tensors are not the right data type
torch.mean(x), x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [55]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [56]:
# Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [57]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [58]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [59]:
x[0]

tensor(1)

In [60]:
# Find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack, vertical stack) or side by side (hstack, horizontal stack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [61]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

The reshape has to be compatible with the original size, so you can't do `(1, 7)` because we have 9 elements and not 7 `1 * 7`.

Something we could do though is when using `arange` we can have the parameters be `(1., 11.)`, so now we have 10 elements, then in `reshape` we can have the paramters be `(5, 2)` and this would work.

In [62]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [66]:
x_stacked_v = torch.vstack([x, x, x, x])
x_stacked_v

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [67]:
x_stacked_h = torch.hstack([x, x, x, x])
x_stacked_h

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [68]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [69]:
# torch.unsqueeze() - adds a single dimensiont to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [70]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(225, 225, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrage the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([225, 225, 3])
New shape: torch.Size([3, 225, 225])


In [71]:
x_original[0][0][0] = 728218
x_original[0][0][0], x_permuted[0][0][0]

(tensor(728218.), tensor(728218.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [72]:
# Create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [73]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [74]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [75]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [76]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [77]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [78]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [79]:
# Get index 0 of 0th and 1st dimensiona nd all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [80]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3, 6, 9
print(x[:, :, 2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want to convert it iton PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [81]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise
# use .type() method to change the data type

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [82]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [84]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural neetwork learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random see**.

Essentially what the random seed does is "flavour" the randomness.

**Extra Resources:**
- https://pytorch.org/docs/stable/notes/randomness.html
- https://towardsdatascience.com/how-to-use-random-seeds-effectively-54a4cd855a79
- https://en.wikipedia.org/wiki/Random_seed

In [85]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1262, 0.4783, 0.6596, 0.2203],
        [0.9340, 0.0026, 0.6991, 0.9398],
        [0.1985, 0.7235, 0.1264, 0.6590]])
tensor([[0.0160, 0.3859, 0.9199, 0.8459],
        [0.9038, 0.5150, 0.0600, 0.4425],
        [0.2936, 0.6100, 0.4214, 0.3501]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [86]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42 # The number here represents the different flavour of randomness

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of estup and requires the investment of purchasing a GPU, there's lots of options...
3. use cloud computing - GCP (Google Cloud Platform), AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation.

### 2. Check for GPU access with PyTorch

In [87]:
# Check for GPU access with PyTorch
import torch

torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html

E.g. run on GPU if available, else default to CPU

In [88]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [89]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [90]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [91]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [92]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

In [ ]:
# The tensor on the GPU still remains unchanged
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-curriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises