# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [21]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [22]:
# Import torch
import torch

# Create random tensor
rand_one = torch.rand(7, 7)
rand_one

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518],
        [0.4681, 0.6738, 0.3315, 0.7837, 0.5631, 0.7749, 0.8208],
        [0.2793, 0.6817, 0.2837, 0.6567, 0.2388, 0.7313, 0.6012],
        [0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343, 0.7893, 0.3216, 0.5247],
        [0.6688, 0.8436, 0.4265, 0.9561, 0.0770, 0.4108, 0.0014],
        [0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
# Create another random tensor
rand_two = torch.rand(1, 7)

# Perform matrix multiplication 
multiplied_matrix = torch.matmul(rand_one, rand_two.T)
multiplied_matrix

tensor([[1.5166],
        [3.1874],
        [2.5350],
        [2.8343],
        [2.6844],
        [2.6483],
        [2.4059]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(RANDOM_SEED)
random_one = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
random_two = torch.rand(1, 7)

# Matrix multiply tensors
multiplied_tensors = torch.matmul(random_one, random_two.T)
multiplied_tensors

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [49]:
# Set random seed on the GPU
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [50]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
gpu_tensor_one = torch.rand(2, 3).to(DEVICE)

torch.manual_seed(RANDOM_SEED)
gpu_tensor_two = torch.rand(2, 3).to(DEVICE)

print(f"Device: {DEVICE}")
gpu_tensor_one, gpu_tensor_two

Device: cuda


(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [45]:
# Perform matmul on tensor_A and tensor_B
multiplied_gpu_matrix = torch.matmul(gpu_tensor_one, gpu_tensor_two.T)
multiplied_gpu_matrix

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [46]:
# Find max
max_output = torch.max(multiplied_gpu_matrix)

# Find min
min_output = torch.min(multiplied_gpu_matrix)

max_output, min_output


(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [47]:
# Find arg max
max_index_output = torch.argmax(multiplied_gpu_matrix)

# Find arg min
min_index_output = torch.argmin(multiplied_gpu_matrix)

max_index_output, min_index_output

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed
RANDOM_SEED = 7

# Create random tensor
torch.manual_seed(RANDOM_SEED)
last_random_tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_output = torch.squeeze(last_random_tensor)

# Print out tensors and their shapes
last_random_tensor, last_random_tensor.shape, squeezed_output, squeezed_output.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))